<?php

$english = array(
    
    /** 
     * Form Builder Page
     */
    'hj:formbuilder:sidebartitle' => 'Form Details',
    'hj:formbuilder:bodytitle' => 'Form Fields',
    'hj:formbuilder:sidebardescription' => 'Select a form you would like to edit',
    'hj:formbuilder:newform' => 'Create new form',
    'hj:formbuilder:newfieldform' => 'Create new field',
    'hj:formbuilder:addnewfield' => 'New field',
    'hj:formbuilder:defineformfirst' => 'Fields are not yet available. Please create a new form or choose an existing one from the dropdown on the left',
    'hj:formbuilder:addfield' => 'Add new field',
    'hj:formbuilder:deleteform' => 'Delete Form',
    'hj:formbuilder:addsections:sueccess' => 'Sections updated successfully',
    /**
     * Form labels and hints
     */
    
    'hj:formbuilder:select' => 'Select...',
    'hj:formbuilder:formsdropdown:new' => 'Create new form',
    
    'hj:formbuilder:label:form_title' => 'Unique Form Name',
    'hj:formbuilder:label:form_label' => 'Title / Header',
    'hj:formbuilder:label:form_description' => 'Description / Subtitle',
    'hj:formbuilder:label:form_action' => 'Action',
    'hj:formbuilder:label:form_method' => 'Method',
    'hj:formbuilder:label:form_enctype' => 'Encryption Type',
    'hj:formbuilder:label:form_class' => 'Additional CSS classes',
    'hj:formbuilder:label:form_access' => 'Access Level',
    'hj:formbuilder:label:form_eval' => 'Apply PHP eval() to certain fields',
    'hj:formbuilder:label:form_type' => 'ElggEntity type and subtype this form will create/edit',
    'hj:formbuilder:label:on_submit' => 'Things to do with the result of form submission',
    'hj:formbuilder:notify_admins' => 'Notify Administrators',
    'hj:formbuilder:add_to_river' => 'Add to River Stream',
    'hj:formbuilder:comments_on' => 'Allow Comments',
    'hj:formbuilder:submitviajax' => 'Submit form via AJAX call',
    'hj:formbuilder:label:container_type' => 'Entity type and subtype this form will create',
    
    'hj:formbuilder:hint:form_url' => '<b>URL:</b> %s',
    'hj:formbuilder:hint:form_guid' => '<b>GUID:</b> %s',
    'hj:formbuilder:hint:form_action' => 'Default action <i>action/framework/entities/save</i> will save the form as an instance of hjFormSubmission and notify the admin that the form was submitted',
    'hj:formbuilder:hint:form_eval' => 'Some of the fields can be treated as PHP command strings, as to enable dynamic forms',
    
    'hj:formbuilder:label:field_type' => 'Field Type',
    'hj:formbuilder:label:field_name' => 'Unique Name (no spaces, one per form)',
    'hj:formbuilder:label:field_label' => 'Label',
    'hj:formbuilder:label:field_value' => 'Default value to set',
    'hj:formbuilder:label:field_class' => 'Additional CSS properties',
    'hj:formbuilder:label:field_mandatory' => 'Mandatory field?',
    'hj:formbuilder:label:field_disabled' => 'Disable editing?',
    'hj:formbuilder:label:field_options' => 'List options',
    'hj:formbuilder:label:field_options:beginner' => 'List of options',
    'hj:formbuilder:label:field_options_values' => 'List an array of options and values',
    
    'hj:formbuilder:hint:field_label' => 'This value can then be translated using language files',
    'hj:formbuilder:hint:field_options' => 'PHP string, array or function',
    'hj:formbuilder:hint:field_options:beginner' => 'Comma-separated list of values for checkboxes, radio inputs and dropdowns',

    'hj:formbuilder:label:section' => 'ONLY If you are creating a NEW SECTION for one of the hypeJunction plugins, enter the name of the section here. Make it a unique name (without spaces). It must not coincide with other object sybtypes in the system',
    /**
     * Form Submissions
     */    
    'hj:formbuilder:submissionfor' => 'Submission for %s',
    'hj:formbuilder:hint:submissions_url' => '<b>Submissions</b>: %s',
    'hj:formbuilder:submissionfield' => '<div><b>%s:</b> %s <br /></div>',
    'hj:formbuilder:formsubmissions' => 'Form Submissions for %s',
    'hj:formbuilder:allforms' => 'all forms',
    
    'hj:formbuilder:admin:sections' => 'hypeFormBuilder allows you to easily generate new forms and update the existing ones.<br />
        Below, you see a list of subtypes that are generated by one (or more) of the forms available in hypeFormBuilder<br/>
        You can create unique sections by adding new forms to the hypeFormBuilder and assigning them a unique subtype name (those will be then shown in this list).
    ',
    
    'hj:formbuilder:addsections:success' => 'Section changes were saved',
    );

add_translation("en", $english);
?>